### ISSUE TITLE
Import of `fsspec/implementations/arrow.py` fails due to 3.8+ code

### ISSUE THREAD

**Issue by philsc** [fsspec/filesystem_spec#1165]
We're seeing this error with the new `2023.1.0` release on Python 3.7:
```
ImportError:
 cannot import name 'cached_property' from 'functools' 
(/var/.../python3.7/lib/python3.7/functools.py)
```
This is happening because `cached_property` only exists on Python 3.8 or higher.
https://docs.python.org/3/library/functools.html#functools.cached_property

Looks like this was introduced in #1122.

Solutions I see:
1. Use the pip package on 3.7: https://pypi.org/project/cached-property/
2. Bump minimum required Python version to 3.8.

**Comment by martindurant** [comment]
We should probably remove py37, as so many adjacent OSS repos already have. However, there's not really a way to go back and fix someone installing this version and facing the specific import error. 
Pyarrow does still release for py37, but conda-forge no longer builds these.
