### PR TITLE
Fix cat_ranges on filecache and on targets without on_error (follow-up to #2154)

### PR DESCRIPTION
**Pull request by itzzdev09**
Follow-up to #2154, fixing the two problems @lhoupert found while merging main into #2075.

**filecache `_cat_ranges` raised `AttributeError`.** #2154 put the new `_local_paths_for_ranges` helper on `SimpleCacheFileSystem`, but the async `_cat_ranges` that calls it is defined on `WholeFileCacheFileSystem`, so filecache could not find it:

```python
await filecache_fs._cat_ranges(["memory://f"], [0], [4])
# AttributeError: ... has no attribute '_local_paths_for_ranges'
```

The helper now lives on `WholeFileCacheFileSystem`. It also accepts what filecache's `_check_file` returns for a cached file (`(detail, fn)`, or `False` when missing), as well as simplecache's plain path.

**`on_error` was passed to `get()`/`_get()`.** Neither takes it, so it ended up in the target's `get_file`, and implementations without `**kwargs` (e.g. `http_sync`) raise `TypeError`. It is no longer passed there. It is still used for the local `cat_ranges` that reads the ranges.

Tests, all in `test_cached.py`:
- `test_async_cat_ranges_downloads_uncached` for filecache and simplecache, including a second call that reads the cached files.
- `test_simplecache_cat_ranges_target_get_file_without_on_error`, with a target whose `get_file` has no `**kwargs`.

The filecache and strict `get_file` cases fail on master, and `test_cached.py` passes.

This overlaps with #2101 and #2075, which also touch these methods. Happy to rebase if either lands first.

### CODE REVIEW

**Comment by itzzdev09** [comment]
The CI failures are from master: test_fast_slice_pypy_fallback has been failing since #2093. Fixed in [fsspec/filesystem_spec#2164](https://github.com/fsspec/filesystem_spec/pull/2164)

**Comment by martindurant** [comment]
(I'll merge that shortly ,and you can update here)

**Comment by martindurant** [comment]
Out of interest: how many implementations lack on_error?

**Comment by itzzdev09** [comment]
None of them, as far as I can tell: every get_file/_get_file in fsspec/implementations takes **kwargs. The problem is the ones that pass those kwargs on to their client. http_sync does session.get(url, **kw), so requests raises TypeError: unexpected keyword argument 'on_error', and async http does the same via aiohttp. Everywhere else it's silently swallowed, which isn't much better, since get() never had an on_error to begin with. I'd expect s3fs/gcsfs to behave like the HTTP ones since they forward kwargs to the client call too.

**Comment by martindurant** [comment]
I should have said: are there implementations that don't *use* on_error; but we do also have "special" implementations like caches and the asyns wrapper to make life more complicated.

**Comment by itzzdev09** [comment]
Good question, and my PR description was sloppy: http_sync does take **kwargs, it just passes them straight to requests.get, which is where the TypeError comes from. Same with async http and aiohttp. I'll fix the wording.

On the actual question: none of them use on_error. No get/_get declares it anywhere, base classes included, so it's always just a passthrough kwarg. It lives on cat/cat_ranges/copy/walk instead.

And yeah, the special ones don't help. Caches hand get to the target so it ends up in its get_file, and the async wrapper passes whatever it gets to the wrapped sync get. The caches do implement on_error on their own cat/cat_ranges, which is probably how it ended up here in the first place.
